WIP: modals and tailwind conf
DigiChanges/react-experience pull request #5
Opened 2020-10-09 15:00 UTC by JeremiasKoch

2020-10-11 16:26 UTC, Murzbul requested changes

2020-10-11 16:26 UTC, Murzbul commented on SchemaValidations/SignUpSchema.js
> +  email: Yup.string().email("Invalid email").required("Required"),
Tanto el email como el required deberian estar abajo para que tenga el misom formato q los demas elementos,

2020-10-11 16:26 UTC, Murzbul commented on Templates/ForgotPassword/index.js
> +const Login = () => (
Me parece que deberia tener como nombre ForgotPassword.

2020-10-11 16:26 UTC, Murzbul commented on Templates/Tables/UsersTable/index.js
> +  React.useEffect(() => {
Este segundo para que lo usas?

2020-10-11 16:26 UTC, Murzbul commented on Templates/Tables/UsersTable/index.js
> +  const columns = [
Las columnas deberian estar en otro archivo.

2020-10-11 16:26 UTC, Murzbul commented on Templates/Tables/UsersTable/index.js
> +      cell: (row, rowIndex) => {
La idea es generar un archivo aparte.

2020-10-11 16:26 UTC, Murzbul commented on Templates/Tables/UsersTable/index.js
> +      cell: (row, rowIndex) => {
Idem como habiamos hablado.

2020-10-11 16:26 UTC, Murzbul commented on Templates/Tables/UsersTable/index.js
> +  const CustomLoader = () => (
Esto es un componente aparte.

2020-10-11 16:26 UTC, Murzbul commented on Templates/Tables/UsersTable/index.js
> +              <svg
Faltaria tambien la separacion de todos los atomos con respecto a los iconos.

2020-10-13 12:42 UTC, JeremiasKoch commented on Templates/Tables/UsersTable/index.js
> +  React.useEffect(() => {
Lo uso para mantener la animación de loading activada, el useEffect la pasa a false y corta la animación

2020-11-04 14:58 UTC, Murzbul commented on atoms/Select.tsx
> +const MultiSelectTwo: React.FC<OwnProps & FieldProps> = ({
Deberias cambiarle  el nombre

2020-11-04 14:58 UTC, Murzbul commented on atoms/Select.tsx
> +  console.log(selectProps);
tendrias q sacar el  log

2020-11-04 14:58 UTC, Murzbul commented on atoms/Select.tsx
> +          primary25: "#4a5568",
Estos colores deberian poder ingresar mediante props para poder darle un  estilo sin cambiar el componente.

2020-11-04 14:58 UTC, Murzbul commented on templates/users/UserChangePass.tsx
> +      <section className="text-gray-500 body-font bg-gray-900 h-screen w-1/4 flex justify-center items-center">
Aca sigue estando el porcentaje

2020-11-04 14:58 UTC, Murzbul commented on templates/users/UserCreate.tsx
> +    <section className="text-gray-500 body-font bg-gray-900 w-128">
idem

2020-11-29 22:12 UTC, merged